name: Actions Workflow

#on: [push]
on: [pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Docker Action
        id: hello
        uses: ./.github/actions/hello-docker
        with: 
          who-to-greet: Brian
      - name: Log Greeting Time
        run: |
          echo "Time: ${{ steps.greet.outputs.time }}"
          echo $HELLO
          